version: '3.7'

volumes:
  images:

services:
  frontend:
    build: ../frontend/docker
    environment:
      API_URL: /entries
    ports:
      - "80:80"
    volumes:
      - images:/usr/share/nginx/html/images
      - ./conf:/etc/nginx/conf.d
    links:
      - backend

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/guestbook-0.1.0.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: memory
      GUESTBOOK_IMAGES_LOCAL_URLPREFIX: /images
      GUESTBOOK_IMAGES_LOCAL_FILEPATH: /images/
    volumes:
      - images:/images
