version: '3.7'

volumes:
  images:

services:
  frontend:
    image: "paksv.local.test/guestbook-frontend:${FRONTEND_VERSION:-latest}"
    environment:
      API_URL: /entries
    ports:
      - "80:80"
    volumes:
      - images:/usr/share/nginx/html/images
      - ./conf:/etc/nginx/conf.d
    links:
      - backend

  backend:
    image: "paksv.local.test/guestbook-backend:${BACKEND_VERSION:-latest}"
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: memory
      GUESTBOOK_IMAGES_LOCAL_URLPREFIX: /images
      GUESTBOOK_IMAGES_LOCAL_FILEPATH: /images/
    volumes:
      - images:/images
